Add new project flow
SabinaValeriia/intership-second pull request #10
Opened 2023-11-21 19:51 UTC by SabinaValeriia

2023-11-22 08:53 UTC, kovalenk requested changes
Як воно працює я не дивився так як тут дуже багато треба чого міняти, тож очікую на правки

2023-11-22 08:53 UTC, kovalenk commented on src/assets/icons/foto.svg
тут треба завантажувати тільки іконку що всередині, сам же контур тобиться на фронті (він потім мінятись по стилям буде)

2023-11-22 08:53 UTC, kovalenk commented on src/components/common/DropdownComponent.vue
> +        p {{ item.leadName }}
Це як обговорювалось треба винести в окремий компонент, і там де img повинний бути кондішн чи то іконка чи картинка чи взагалі його не буде

2023-11-22 08:53 UTC, kovalenk commented on src/components/common/DropdownComponent.vue
> +  if (!selectedItems.value.includes(item)) {
ось це треба робити в фільтрації, нам не повинно показуватись опції яка вже вибрана, замість того щоб ось тут це перевіряти

2023-11-22 08:53 UTC, kovalenk commented on src/modals/AppModal.vue
> +  .modal(:class="{ create: create }")
якщо в тебе зміна сходиться з назвою клас, то **create: create** можна не писать **{ create }**

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +                | JPG, PNG, WEBP (up to 5 mb)
| JPG, PNG, WEBP (up to 1 mb)

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +    .form-group {
не бачу щоб form-group був винесений, тут же треба було використовувати стилі які вже були зроблені в логінці, зараз бачу купа повторень тож це треба виносити

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +        form(@submit.prevent="submit")
@submit.prevent="submit" не використовується

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const showAdd = ref(true);
це пивинен бути computed а не статика, і вони відповідають за одне й теж

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const membersShow = ref(false);
це теж  пивинен бути computed а не статика

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const membersNames = ref([]);
ці дві змінні відповідають за одне

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const showMembers = ref(false);
ось це треба зробити інакше, замість того щоб створювати купу змін (вспоминай коли ти робила toggle switcher

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +};
ось це треба переробити, там воно повинно просто пушитись в масив без всіляких перевірок

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +  }
прибрати

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const deleteTag = (tag) => {
типізації немає

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +}
інтерфейси вверху пишем

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +};
це повинно бути в вотчері на title  👇

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +  });
нема повідомлення про успішне додавання, також catch повинен бути

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const emit = defineEmits(["close"]);
emit зазвичай йде вверху

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +    console.log(data);
прибрати

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +    membersNames.value = leadNames.value;
тут вище комент я залишив

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +}
це треба винести в AppModal

2023-11-22 08:53 UTC, kovalenk commented on src/modals/ModalCreate.vue
По структурі коду, згрупуй все більш красиво (ось приклад як все повинно бути)

1. Imports
2. Interfaces
3. props
4. emits
5. data
6. watch
7. computed
8. methods
9. hooks

2023-11-22 08:53 UTC, kovalenk commented on src/scss/_form.scss
> +        }
!important;

2023-11-22 08:53 UTC, kovalenk commented on src/services/api/projectApi.ts
> +};
не бачу взагалі типізації

2023-11-22 08:53 UTC, kovalenk commented on src/services/api/tagsApi.ts
> +export const showTags = (): Promise<AxiosResponse> => {
тут теж нема типізації

2023-11-22 08:53 UTC, kovalenk commented on src/services/api/userApi.ts
> +export const showUsers = (): Promise<AxiosResponse> => {
тут теж нема типізації

2023-11-22 09:53 UTC, SabinaValeriia commented on src/assets/icons/foto.svg
+

2023-11-22 09:53 UTC, SabinaValeriia commented on src/modals/AppModal.vue
> +  .modal(:class="{ create: create }")
+

2023-11-22 09:54 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +                | JPG, PNG, WEBP (up to 5 mb)
+

2023-11-22 09:56 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +        form(@submit.prevent="submit")
+

2023-11-22 14:43 UTC, SabinaValeriia commented on src/components/common/DropdownComponent.vue
> +        p {{ item.leadName }}
+

2023-11-22 14:43 UTC, SabinaValeriia commented on src/components/common/DropdownComponent.vue
> +  if (!selectedItems.value.includes(item)) {
+

2023-11-22 14:43 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +    .form-group {
+

2023-11-22 14:44 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +const membersNames = ref([]);
+

2023-11-22 14:45 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +const showMembers = ref(false);
+

2023-11-22 14:46 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +  }
+

2023-11-22 14:48 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +const deleteTag = (tag) => {
+

2023-11-22 14:49 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +}
+

2023-11-22 14:50 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +};
+

2023-11-22 14:53 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +  });
+

2023-11-22 14:53 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +const emit = defineEmits(["close"]);
+

2023-11-22 14:54 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +    console.log(data);
+

2023-11-22 14:59 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +}
+

2023-11-22 15:19 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
+

2023-11-22 15:19 UTC, SabinaValeriia commented on src/scss/_form.scss
> +        }
+

2023-11-22 15:32 UTC, SabinaValeriia commented on src/services/api/projectApi.ts
> +};
+

2023-11-22 15:38 UTC, SabinaValeriia commented on src/services/api/tagsApi.ts
> +export const showTags = (): Promise<AxiosResponse> => {
+

2023-11-22 15:39 UTC, SabinaValeriia commented on src/services/api/userApi.ts
> +export const showUsers = (): Promise<AxiosResponse> => {
+

2023-11-22 17:28 UTC, SabinaValeriia commented
![Снимок экрана 2023-11-22 в 18 11 22](https://github.com/SabinaValeriia/intership-second/assets/116557806/dc1a3e21-9198-4d07-8e78-6b0b290d8b5f)
![Снимок экрана 2023-11-22 в 18 14 53](https://github.com/SabinaValeriia/intership-second/assets/116557806/3a7596c0-454c-4f20-a95c-0578fa9fd231)

2023-11-27 08:04 UTC, kovalenk requested changes

2023-11-27 08:04 UTC, kovalenk commented on src/components/common/BaseInput.vue
> +  label {{ capitalizeFirstLetter(`${type}`) }}
на мобільних девайсах arrow повинен бути на одному рівні з label і закриття також вонинно бути на ньому, нині я бачу що воно працює чомусь на інпуті

2023-11-27 08:04 UTC, kovalenk commented on src/components/common/BaseInput.vue
> +    .grey-circle(v-if="type === 'lead'")
префікси і суфікси повинні бути слотами

2023-11-27 08:04 UTC, kovalenk commented on src/components/common/BaseInput.vue
> +};
типізацію не забувай word: ____. type: ____.

2023-11-27 08:04 UTC, kovalenk commented on src/components/common/DropdownList.vue
> +    p {{ item.tag }}
це не реалізовано так як ми говорили

2023-11-27 08:04 UTC, kovalenk commented on src/components/common/DropdownList.vue
> +};
в цьому компоненті не повинно бути ніяких фільтрацій, він тільки приймає список і віддає елемент на який натиснули

2023-11-27 08:04 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const showAdd = ref(true);
не виправлено

2023-11-27 08:04 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +};
це не винесено в окремий компонент

2023-11-27 08:04 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +      cursor: pointer;
це винести разом в окрему компоненту де буде image input (разом з логікою що виділив вище)

2023-11-27 08:04 UTC, kovalenk commented on src/scss/_form.scss
форма дуже переповнена, там непотрібно тримати стилі тегів мемберів і так далі. Тут прописані основні стилі які указані в фігма (всі можливі кейси) Якщо додається чи префікс/суфікс він уже повинен бути прописаний тут розміром 20/16 як те указано в фігма. Слотами тільки перекидуємо сам контент іконки і все, і не треба під кожен випадок називати по інакшому, щоб в стилях зберігались тучу непотрібного.  
Вспомни що я казав, цей компонент повинен повторно використовуватись з мінімальними правками, в тебе це не вийшло на данний момент

2023-11-27 08:34 UTC, kovalenk commented
1) не видаляється key коли стираємо title

<img width="638" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/17783b73-2986-4859-a6c1-6a16d3b47f24">

2) поїхала верстка 

<img width="161" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/0aceae03-a387-471b-a29c-226277e4c760">

3) не показується данні, перші 4-5 елементів повинні показуватись, якщо їх нема то показувати відповідне повідомлення.

<img width="258" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/de7a5e8a-ddba-4b4a-b3ac-18a147370783">

4) Також попап не закривається коли інший відкрили 

<img width="590" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/9a9faaf5-ccc1-4051-8234-3f7a30c2cf2e">

5) Данні є але вони не показуються 

<img width="376" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/4fdd4a04-88b1-48db-969b-a7549284359c">

6) Шрифт не той 
<img width="650" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/0d3d94c7-13b7-4ba8-b75a-054f756f520d">

7) тогл працює некоректно і без візуалізації як на фігма

<img width="366" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/bdbf1131-b8cc-49d6-9087-8256f94a0109">

8) Проблеми з версткою, розміри не ті 

<img width="364" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/43934b5b-45a7-48e8-9c5d-0f4ee9dba8c7">

9) Елементи не по центру 

<img width="359" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/43a6b7aa-ead1-4f7f-adfe-38707f868f06">

10) Розміри шрифтів передивитись на мобільному

2023-11-27 09:38 UTC, SabinaValeriia commented on src/components/common/BaseInput.vue
> +  label {{ capitalizeFirstLetter(`${type}`) }}
+

2023-11-27 09:39 UTC, SabinaValeriia commented on src/components/common/BaseInput.vue
> +    .grey-circle(v-if="type === 'lead'")
+

2023-11-27 09:40 UTC, SabinaValeriia commented on src/components/common/BaseInput.vue
> +};
+

2023-11-27 10:02 UTC, SabinaValeriia commented on src/components/common/DropdownList.vue
> +    p {{ item.tag }}
+

2023-11-27 10:03 UTC, SabinaValeriia commented on src/components/common/DropdownList.vue
> +};
+

2023-11-27 10:32 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +};
+

2023-11-27 10:33 UTC, SabinaValeriia commented on src/modals/ModalCreate.vue
> +      cursor: pointer;
+

2023-11-27 15:09 UTC, kovalenk requested changes

2023-11-27 15:09 UTC, kovalenk commented on src/components/common/BaseInput.vue
> +    slot(name="icon")
slot(name="prefix")

2023-11-27 15:09 UTC, kovalenk commented on src/components/common/BaseInput.vue
> +    slot(name="arrow")
slot(name="sufix") 
Називай слоти правильно, в фігма показано що стрілка буде появлятись тільки один раз 
<img width="1019" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/130a3e70-6dc6-4454-95ef-6e9b98c3077f">

2023-11-27 15:09 UTC, kovalenk commented on src/components/common/DropdownList.vue
> +      .grey-block(v-else)
лого бачу, іконки, чекбокса не бачу

2023-11-27 15:09 UTC, kovalenk commented on src/components/common/ImageInput.vue
> +        console.log(userImage);
продивляйся і удаляй логи перед тим як пушити

2023-11-27 15:09 UTC, kovalenk commented on src/modals/ModalCreate.vue
>      members.value.push(tag.id.toString());
тут знову фільтрація зроблена не так, я вже повертав тобі цю задачу (для того щоб не робити ось такі страшні кондішни ти повинна фільтрувати список відносно того що ти вибрала) Зараз же ти фільтруєш навпаки коли вибираєш із за чого твій код не читабельний і з багами

2023-11-27 15:09 UTC, kovalenk commented on src/modals/ModalCreate.vue
> +const addFile = (userImage) => {
типізацію не забуваємо, більше таких помилок не хочу бачити

2023-11-27 15:19 UTC, kovalenk commented
1) стрілки навпаки повинні працювати
<img width="390" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/ccf662cc-f212-4274-a0d2-0ac9de4ddf38">
2) розміри!!!
<img width="371" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/b447d239-d379-491c-885d-e08be91b60e7">

2023-12-08 08:01 UTC, kovalenk commented
цей ПР буде в наступному, тому закриваю його

2023-12-08 08:01 UTC, closed without merging