V  project page
SabinaValeriia/intership-second pull request #11
Opened 2023-11-25 18:30 UTC by SabinaValeriia

2023-11-27 10:38 UTC, kovalenk requested changes

2023-11-27 10:38 UTC, kovalenk commented on src/assets/icons/star-notify.svg
<img width="1420" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/9e4f1116-536d-4dfe-82db-07cd23e40727">
ці дві картинки повинні бути одною іконкою, міняти колір про маску

2023-11-27 10:38 UTC, kovalenk commented on src/components/HeaderComponent.vue
> +        )
перехід повинен бути по "View all"
<img width="452" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/517aec38-6473-44cf-8202-1f1ce76536d1">

2023-11-27 10:38 UTC, kovalenk commented on src/components/NoResults.vue
> +  common-button.btn-secondary(@click="reset") Reset
оптимізувати, в тебе структура шаблонна, зараз в 2рази більше коду

2023-11-27 10:38 UTC, kovalenk commented on src/components/common/CommonLoader.vue
щодо лоадера глянути, бо він геть не такий як показано в фігма (дьорганий, пропорції не ті)

2023-11-27 10:38 UTC, kovalenk commented on src/components/common/DropdownMenu.vue
> +        p(v-for="(item, index) in tagNames", :key="index") {{ index === 0 ? item.tag : "" }}
це також оптимізувати, stared поки не треба показувати

2023-11-27 10:38 UTC, kovalenk commented on src/components/common/DropdownMenu.vue
> +  showTag();
нащо тут теги?

2023-11-27 10:38 UTC, kovalenk commented on src/components/common/PaginationComponent.vue
> +</script>
якщо копіюєш звідкись то хочаб перероблюй під vue3

2023-11-27 10:38 UTC, kovalenk commented on src/composables/projectsAction.ts
> +};
типізація, я кожного разу не буду це повторювати

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +    no-results(
нема кондішна на no-results він в тебе весь час показується 

<img width="1792" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/db529dcd-0583-4ecb-993f-b1e68b35c7f6">

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +const tags = ref();
теги в композаблі вже повинні бути

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +const itemsPerPage = ref(10);
ми показуємо 8 елементів на сторінку

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +const itemsPerPage = ref(10);
дуже багато змін дублюють один одного, розберись і правильно до купи їх зʼєднай (композабли теж ніхто не забороняв)

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +  }
пагінація на сервері працює а не на фронті, фільтрація теж

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +const itemsPerPage = ref(10);
<img width="1792" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/988f5068-1fba-41ff-bcaf-5a9bf9d65c4d">

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +  return function (value) {
ми так не робимо   return function (value) {

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +};
це реалізувати відносно розміру екрану (ми це вже робити на інших проектах, на це є міксіна)

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +  });
Розібратись з цим, в тебе токен ніяк не враховується 
<img width="618" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/514acf8d-9a04-4459-b6e0-250b55b8452f">

2023-11-27 10:38 UTC, kovalenk commented on src/views/ProjectsView.vue
> +    no-results(
Create не працює

2023-11-27 19:20 UTC, SabinaValeriia commented on src/components/common/DropdownMenu.vue
> +  showTag();
+

2023-11-27 19:21 UTC, SabinaValeriia commented on src/assets/icons/star-notify.svg
+

2023-11-27 19:21 UTC, SabinaValeriia commented on src/components/HeaderComponent.vue
> +        )
+

2023-11-27 19:21 UTC, SabinaValeriia commented on src/components/NoResults.vue
> +  common-button.btn-secondary(@click="reset") Reset
+

2023-11-27 19:21 UTC, SabinaValeriia commented on src/components/common/PaginationComponent.vue
> +</script>
+

2023-11-27 19:33 UTC, SabinaValeriia commented on src/composables/projectsAction.ts
> +};
+

2023-11-27 19:45 UTC, SabinaValeriia commented on src/views/ProjectsView.vue
> +const itemsPerPage = ref(10);
+

2023-11-27 19:45 UTC, SabinaValeriia commented on src/views/ProjectsView.vue
> +const tags = ref();
+

2023-11-27 19:46 UTC, SabinaValeriia commented on src/views/ProjectsView.vue
> +  return function (value) {
+

2023-11-27 19:47 UTC, SabinaValeriia commented on src/views/ProjectsView.vue
> +};
+

2023-11-27 19:47 UTC, SabinaValeriia commented on src/views/ProjectsView.vue
> +  });
+

2023-11-27 19:49 UTC, SabinaValeriia commented on src/views/ProjectsView.vue
> +const itemsPerPage = ref(10);
+

2023-11-27 19:50 UTC, SabinaValeriia commented on src/components/common/DropdownMenu.vue
> +        p(v-for="(item, index) in tagNames", :key="index") {{ index === 0 ? item.tag : "" }}
+

2023-12-04 10:43 UTC, kovalenk commented
1) Project page запускається некоректно (падає дуже багато помилок) 
<img width="1792" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/b1130900-eb7c-4148-87b0-703737012a9a">
<img width="1792" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/e45d4be1-0f83-4b17-9351-0c73ab17a908">
2) Данні не показались 
<img width="1792" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/fc22d367-48cc-4ce3-9a60-31f01840bede">

2023-12-04 13:03 UTC, kovalenk commented
Сторінка все ще працює погано, в відео описано що саме не так зроблено (слак)

2023-12-08 10:24 UTC, kovalenk commented
1) Некоректно працює лоадер, всі елементи повинні бути скриті на етапі лоадера, показувати тільки хедер таблиці (в фігма є на це скрін) Якщо була використана пагінація (напр сторінка 3, то сторінка повинна бути ресетнута на 1-у)
2) не показувати пагінацію коли фільтр пустий 
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/786919f2-1ee9-45be-b3e4-8db45176e9f1)
3) Пагінація працює некоректно, завжди повертається тільки перша пара проектів
4) multi dd працює не так як описано, також стилі переглянути бо з ними повна біда
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/5ddd9478-437f-4afd-a596-f20ce57e446b)
https://miro.com/app/board/uXjVNRGkKG4=/?moveToWidget=3458764572068574882&cot=14
5) Переробити сортування, в коді не повинно бути статики 
`const activeSort = ref({
  name: { active: false },
  key: { active: false },
  lead: { active: false },
});

 showProjects("_page=1&_limit=8&sort=title:ASC").then((response) => {
      projectsArray.value = response.data.data
        .slice(startIndex, endIndex)
        .map((project: ProjectInterfaceItem) => project.attributes);
      activeSort.value = {
        name: { active: false },
        key: { active: false },
        lead: { active: false },
      };

      activeSort.value[field].active = true;
    });`
6) витягування данних списку проектів також переробити, не повинно бути безліч методів на кожен фільтр чи опцію, (зробити це одним методом з динамічними параметрами до страпі)
7) Name та Lead перенаправляються неправильно, дивитись https://miro.com/app/board/uXjVNRGkKG4=/?moveToWidget=3458764569978470172&cot=14
8) стилі тегів не такі, також передивитись всі стилі тому що тут фонти грають своїм життям, то вони 12 то 14 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/89dc3e4c-fc7c-4916-9c42-5067f339ea0a)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/5323635c-bebd-4432-9459-549272ad6537)

9) Create project не працює, передивитись інтерфейс а також типи данних які відправляються **manager**
10) переробити принцип включення лоадера по setTimeout, також ось це переробити і зробити коректну звязку еміта і пропса (або це можна зробити через computed, але явно не через watch)
`watch(
    () => userStore.projectData,
    (newProjectData) => {
      isLoader.value = true;
      setTimeout(() => {
        projectsArray.value.push(newProjectData.data.attributes);
        isLoader.value = false;
        noDataShow.value = false;
        totalProjects.value = projectsArray.value.length;
      }, 1000);
    }
  );`

10) Create project на мобільному виглядає зовсім погано, дивитись макет уважно!!
https://miro.com/app/board/uXjVNRGkKG4=/?moveToWidget=3458764570601886525&cot=14
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/00769613-0d10-47d4-b19a-db5926a45e8d)
11) search не працює в dd 
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/c96b2589-c6b6-44db-9714-88ea26829397)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/94d64235-4aef-4f04-a138-3421bf56a3cf)
12) на мобайлі тут хедер змінився як 2 тижні тому 
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/0fbca297-bf62-4599-985e-774075ebd81f)


Покращення 
1) Замість картинки юзера якого ще нема треба поставити test-logo (в фігма можна найти в іконках)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/6d988e4a-ac27-4f31-aacd-0078a6819e59)
2) щодо members, гадаю тут я використаю multi dd, в фігма перероблю під це 
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/e5acf4b6-ee12-4159-911b-cd4b7c941c08)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/8891ed8b-eb12-48d6-a05e-8e1575c4e7c2)

2023-12-11 09:24 UTC, kovalenk commented
> 1. Некоректно працює лоадер, всі елементи повинні бути скриті на етапі лоадера, показувати тільки хедер таблиці (в фігма є на це скрін) Якщо була використана пагінація (напр сторінка 3, то сторінка повинна бути ресетнута на 1-у)
> 2. не показувати пагінацію коли фільтр пустий
>    ![image](https://private-user-images.githubusercontent.com/25953935/289032997-786919f2-1ee9-45be-b3e4-8db45176e9f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQ4MTYsIm5iZiI6MTcwMjI4NDUxNiwicGF0aCI6Ii8yNTk1MzkzNS8yODkwMzI5OTctNzg2OTE5ZjItMWVlOS00NWJlLWIzZTQtOGRiNDUxNzZlOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMTljNDYwOTFkNzExOWU2OGVkODcyNzU5YWVmODUwMGRhZGQxMmY4NDNiYTY4MzJhMTNiYjE4MDg4ZTVkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wm-sVYlObWbKJ6mAi8DEVJf7ttfGzxUBwbzyDdzjY_4)
> 3. Пагінація працює некоректно, завжди повертається тільки перша пара проектів
> 4. multi dd працює не так як описано, також стилі переглянути бо з ними повна біда
>    ![image](https://private-user-images.githubusercontent.com/25953935/289033744-5ddd9478-437f-4afd-a596-f20ce57e446b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQ4MTYsIm5iZiI6MTcwMjI4NDUxNiwicGF0aCI6Ii8yNTk1MzkzNS8yODkwMzM3NDQtNWRkZDk0NzgtNDM3Zi00YWZkLWE1OTYtZjIwY2U1N2U0NDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YjhkZjgzYzZkNTYxODczMWUzNDgzYTdlNGEyYzY2NTZkNGUyOWI0ZDI1YTI5NDFiZjZmNzIyNTI0MjI5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vE0Fjui8CCRXhx9E5C8oxpn4EC2U5ijpcJc28Jp6dlQ)
>    https://miro.com/app/board/uXjVNRGkKG4=/?moveToWidget=3458764572068574882&cot=14
> 5. Переробити сортування, в коді не повинно бути статики
>    `const activeSort = ref({
>    name: { active: false },
>    key: { active: false },
>    lead: { active: false },
>    });
> 
> showProjects("_page=1&_limit=8&sort=title:ASC").then((response) => { projectsArray.value = response.data.data .slice(startIndex, endIndex) .map((project: ProjectInterfaceItem) => project.attributes); activeSort.value = { name: { active: false }, key: { active: false }, lead: { active: false }, };
> 
> ```
>   activeSort.value[field].active = true;
> });`
> ```
> 
> 6. витягування данних списку проектів також переробити, не повинно бути безліч методів на кожен фільтр чи опцію, (зробити це одним методом з динамічними параметрами до страпі)
> 7. Name та Lead перенаправляються неправильно, дивитись https://miro.com/app/board/uXjVNRGkKG4=/?moveToWidget=3458764569978470172&cot=14
> 8. стилі тегів не такі, також передивитись всі стилі тому що тут фонти грають своїм життям, то вони 12 то 14
> 
> ![image](https://private-user-images.githubusercontent.com/25953935/289034991-89dc3e4c-fc7c-4916-9c42-5067f339ea0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQ4MTYsIm5iZiI6MTcwMjI4NDUxNiwicGF0aCI6Ii8yNTk1MzkzNS8yODkwMzQ5OTEtODlkYzNlNGMtZmM3Yy00OTE2LTljNDItNTA2N2YzMzllYTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YjIzYjEwNWQyNDMxZjczODA4NTc4Y2ZkMDk4NGJjOTI5ZjUzNGE0YWQ2NTAxYjg2NWJhMjE3NmZhNDE3NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I46xLiWFN1Q5LeJ2j1e3QMr935OdhCk2IAMbcHZIIis) ![image](https://private-user-images.githubusercontent.com/25953935/289035248-5323635c-bebd-4432-9459-549272ad6537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQ4MTYsIm5iZiI6MTcwMjI4NDUxNiwicGF0aCI6Ii8yNTk1MzkzNS8yODkwMzUyNDgtNTMyMzYzNWMtYmViZC00NDMyLTk0NTktNTQ5MjcyYWQ2NTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYWM5MGVhYmU0OWNjYmU3MzdkYzBiZDdjMDczODVkZDRhN2ZjNDA5MjE3MjBhYmEzNWFjMzI5ZDQxNDdjNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cAtkNLV9cwOvsI-ig_1P_i3EcOYgDkOVX0NKl2SbCRw)
> 
> 9. Create project не працює, передивитись інтерфейс а також типи данних які відправляються **manager**
> 10. переробити принцип включення лоадера по setTimeout, також ось це переробити і зробити коректну звязку еміта і пропса (або це можна зробити через computed, але явно не через watch)
>     `watch( () => userStore.projectData, (newProjectData) => { isLoader.value = true; setTimeout(() => { projectsArray.value.push(newProjectData.data.attributes); isLoader.value = false; noDataShow.value = false; totalProjects.value = projectsArray.value.length; }, 1000); }   );`
> 11. Create project на мобільному виглядає зовсім погано, дивитись макет уважно!!
>     https://miro.com/app/board/uXjVNRGkKG4=/?moveToWidget=3458764570601886525&cot=14
>     ![image](https://private-user-images.githubusercontent.com/25953935/289036333-00769613-0d10-47d4-b19a-db5926a45e8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQ4MTYsIm5iZiI6MTcwMjI4NDUxNiwicGF0aCI6Ii8yNTk1MzkzNS8yODkwMzYzMzMtMDA3Njk2MTMtMGQxMC00N2Q0LWIxOWEtZGI1OTI2YTQ1ZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyODMzOTgwZjgzNDc3NmQ1N2JjZjE3ZGJjOWVjNDYyZjE4NzI1MmNkMTNkNGQ1NTdkMGExZjZiYTNlNTkwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kbMXcSwEyM-uzX69FSqMbSJijbbenCNLZvgXBzjIbl8)
> 12. search не працює в dd
>     ![image](https://private-user-images.githubusercontent.com/25953935/289037901-c96b2589-c6b6-44db-9714-88ea26829397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQ4MTYsIm5iZiI6MTcwMjI4NDUxNiwicGF0aCI6Ii8yNTk1MzkzNS8yODkwMzc5MDEtYzk2YjI1ODktYzZiNi00NGRiLTk3MTQtODhlYTI2ODI5Mzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNmQwZjk2NmQwNjY4OGYxMWQxNzk1ZTZmOGM2ODlkYjU4ZTAyMWZiYTlkNTJjZTBmMDdjODI3M2ZlODY1NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wQZkpbV7SyxJKpKQ9R1Pxz9hfwWM5SFTjGCEvGp1Dl8)
>     ![image](https://private-user-images.githubusercontent.com/25953935/289037983-94d64235-4aef-4f04-a138-3421bf56a3cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQ4MTYsIm5iZiI6MTcwMjI4NDUxNiwicGF0aCI6Ii8yNTk1MzkzNS8yODkwMzc5ODMtOTRkNjQyMzUtNGFlZi00ZjA0LWExMzgtMzQyMWJmNTZhM2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YjZmNDlmMWE3NjdlYjJhNWI3ZWE1NTgxMTZhYzY0MjY5Mjc1NGU0MTY4ZjJiYzRhYWI4ODlhMzc1 [...]

2023-12-12 11:25 UTC, kovalenk commented
1) Пагінація (1-неактивна кнопка не ховериться, 2-активна сторінка теж не міняється, 3-стрілка вправо ховериться трохи не так по дизайну) також по дизайну на мобайлі питання, переглянути уважно радіуси і розміри

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/4cf35675-c98f-4ae8-8d03-e8b68078e4d9)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/ea2d9fc6-cab2-4afc-b3a3-b30b472e8749)

2) ці юзери теж повинні бути з лінкою (як і ліди)

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/cbb03af9-739f-40f3-8311-0bde8f5516c8)

3) коли я вибрав юзера то лого юзера показувати, також я не бачу щоб було виправлено ті баги по версткі що я описував вище. Прикріпляю скріни з фігма 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/6d28ab23-8133-4314-85a6-24161ad2ce23)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/14a4a25d-00f7-48af-860a-5c900df6990a)

<img width="792" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/374184ea-8df7-41cc-a295-79ccd904c7c0">
<img width="640" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/774af524-7284-4f1d-a5f9-485aeddbb5c2">

4) на мобайлі кнопки ресет нема, замість неї там іконка. Знову ж прикріпляю як в тебе і макет. Уважніше його робити 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/1e0c428e-424f-4dec-a6b6-5236b3f249d1)
<img width="420" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/5b1aaa6a-9ee2-4a73-b66d-cdf392168d5e">

5) щодо скролу не бачу виправлення 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/d78dbb95-231a-4ffd-905e-608cc37fae0c)

6) Сортування. Коли я перемикаю з Name на Lead то в мене повинно перемкнутись тільки ключ сортування, а не вид сторування. Також при повторному натисненні сортування зовсім зникає (повторюється тільки на lead)

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/894e5579-aec5-4337-8433-b96d69eb08ec)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/34c063a8-2e2a-43d7-969e-8a97505e8e56)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/b6c7d813-ed42-4ec5-8027-e2435cb61da0)

7) Select all не працює так як описано в міро 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/29e16483-932a-4596-b695-bc31d7feb35b)
<img width="868" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/d9d02826-ef7a-4dd1-a1be-f61994e192a0">

8) попередньо що писав не виправлено 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/c8a6239f-8ed6-4d2b-ae4b-b9cbbd29d746)

9) Некоректний флоу на мобільному 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/ac750832-914e-44ad-a8fc-bb56c5899161)
<img width="650" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/9f4008cc-617f-4b39-9eed-22c43be6965a">

10) Теги на мобільному не такі 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/990cd0f8-25bf-47f9-a0cc-77747a0d9525)
<img width="838" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/c2c4ea7e-72fa-44e6-b7fe-29d1da110afd">

11) Ось тут теж показувати іконку юзера, коли я вибрав його, також на мобайлі переглянути розмір arrow-down вона там змінилась з минулих часів

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/5a140210-b2d4-4010-8a33-1486a237b88c)
<img width="834" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/ec246638-0875-4882-9824-833c382c86f7">

12) тут щось не так з розмірами 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/eab0df9f-7131-4d33-904d-57aae500896b)
<img width="490" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/98fce3d7-f7f4-41eb-869e-c42cf43164b9">

13) щось не так з розміткою, (лоадер на мобайлі не відцентровано як на макеті, пагінація повинна бути внизу (статично розмір таблиці 8 елементів, на макеті показано з маленькими/великими розмірами)

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/8714053f-92ff-4737-a4d1-c2abe15ec0fd)

14) Збереження некоректно працює, не закривається модалка і лоадер не ввімкнувся 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/b0f78af7-969c-406b-a069-d486c14945b6)

15) Після збереження не бачу щоб manager виставився коректно. Про це в міро описано 

![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/e4416c27-4a4e-442b-8c00-8b7383f3a4c0)
<img width="702" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/30d06b55-630d-4798-b67b-3d7ecfa0b196">

2023-12-13 09:47 UTC, merged