Add header
SabinaValeriia/intership-second pull request #9
Opened 2023-11-16 13:27 UTC by SabinaValeriia

![Снимок экрана 2023-11-16 в 14 44 22](https://github.com/SabinaValeriia/intership-second/assets/116557806/a54c1785-92ee-49e2-83b2-cdc15e8cf0f9)
![Снимок экрана 2023-11-16 в 14 49 45](https://github.com/SabinaValeriia/intership-second/assets/116557806/2224151c-f78b-4dd6-bfa5-d33b29ec20ea)
![Снимок экрана 2023-11-16 в 15 05 30](https://github.com/SabinaValeriia/intership-second/assets/116557806/7a6d3c5e-6d8b-4e13-8294-bfdfebb9c22e)
![Снимок экрана 2023-11-16 в 15 08 07](https://github.com/SabinaValeriia/intership-second/assets/116557806/2a0a864d-3b06-48de-8a5e-b19547967bde)

2023-11-16 15:52 UTC, kovalenk requested changes
1) Ці подьоргування мені не зовсім подобається, я зараз в фігма зроблю відступи так щоб цих подьоргувань не було зовсім
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/eb8fe2d7-0df0-499c-94a5-544360f2f38b)
2) В макеті не так
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/fda6c892-1256-4fc0-9dc8-b96952b3fe15)
3) До цього додай курсор, також він буде лінкою (потім додамо куди він буде редіректить)
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/5faa743c-2a91-4a8d-9a95-98f45c31b8ef)
4) в тебе навпаки 
<img width="463" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/b3c59d08-31c5-40fb-abc6-b54cc64264bb">
![image](https://github.com/SabinaValeriia/intership-second/assets/25953935/9ec01dc9-0337-417f-a8a8-dc9bd059bb60)

2023-11-16 15:52 UTC, kovalenk commented on src/components/HeaderComponent.vue
> +    )
в кожному img треба додавати alt

2023-11-16 15:52 UTC, kovalenk commented on src/components/HeaderComponent.vue
> +      :src="require(`@/assets/icons/avatar.svg`)",
тут не повинно бути хардкоду, в тебе вже є доступ до данних які приходять зі страпі (попередня задача) Також в макеті показав що якщо немає картинки (нинішній варіант) то ми пишемо букви

2023-11-16 15:52 UTC, kovalenk commented on src/components/HeaderComponent.vue
> +    img.avatar(:src="require(`@/assets/icons/avatar.svg`)")
чомусь іконки іноді як **i.ico** а тут вони як img, іконки це іконки а img то img не плутати

2023-11-16 15:52 UTC, kovalenk commented on src/composables/modalActions.ts
> +export function openModal(key: string) {
function замінити на const і зробити стрілочну функцію

2023-11-16 15:52 UTC, kovalenk commented on src/composables/modalActions.ts
> +export function isOpen(key: string) {
function замінити на const і зробити стрілочну функцію

2023-11-16 15:52 UTC, kovalenk commented on src/layouts/MainLayout.vue
>    router-view
прибрати **transition(name="fade", mode="out-in")**

2023-11-16 15:52 UTC, kovalenk commented on src/modals/ModalHeader.vue
> +      img(:src="require(`@/assets/icons/logo_modal.svg`)")
alt додати

2023-11-16 15:52 UTC, kovalenk commented on src/modals/ModalHeader.vue
> +      img(:src="require(`@/assets/icons/avatar.svg`)")
оці ж данні треба брати зі стора, alt додати

2023-11-16 15:52 UTC, kovalenk commented on src/router/routes.ts
> +  },
в тебе 2 layout ведуть на `path: "/",` це дуже груба помилка, пропоную робочу зону після авторизації назвати, "dashboard"

2023-11-16 15:52 UTC, kovalenk commented on src/components/FooterComponent.vue
> +        color: var(--background);
чому &:hover { знаходиться в кожного елемента окремо, замість того щоб буть у  parent (я про це вже неодноразово говорив)

2023-11-17 10:44 UTC, kovalenk requested changes
1) подьоргування не виправлено 
<img width="494" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/05565f5b-a688-4939-a1dc-9743c05eeda0">

2) Ось тут також ховер не повинен двигати елементи 
<img width="162" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/7e2d7a4a-54f5-44c6-8d24-2c56ee393ef4">

3) редірект працює некоректно /dashboard -> /projects 

4) немає quards на перевірку чи я авторизований, я можу вписати потрібне посилання в урлі і перейти успішно

5) в макеті active не такий 
<img width="207" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/4b37bbb5-cf11-4ef5-8aed-ec9dbede5d7e">

6) Після логіну в локалсторі нічого не завантажилось 
<img width="777" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/db1779f8-c886-499f-a670-a47e360aba2f">
<img width="630" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/3d4c5f51-fb2d-476e-bb1b-6a551461edfc">

2023-11-20 13:32 UTC, kovalenk requested changes
1) стрілка не по центру 
<img width="125" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/4a3ea942-8f38-4521-945c-4aa7af490e89">
2) в юзері кольори поплутала (при ховері на юзера міняється розмір)
<img width="267" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/ed3765da-cd1e-490a-ac5b-378d94596e27">₴
<img width="103" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/2baa4a3c-007c-461a-a20f-761e567021fa">
3) це не виправлено 
<img width="127" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/e91b9aa4-b912-4701-aa51-7740396e7ccf">
4) тут ховер не треба 
<img width="364" alt="image" src="https://github.com/SabinaValeriia/intership-second/assets/25953935/72c7d72c-ab8d-4a00-98d0-a846a4794262">

2023-11-20 13:32 UTC, kovalenk commented on src/components/HeaderComponent.vue
> +            }
це не треба робити через :active, тут повинен бути active клас, який слідить за роутами

2023-11-20 13:32 UTC, kovalenk commented on src/router/routes.ts
> +    }
тут треба ще перевірку якщо ми на логін попали вже авторизованими то кидать на дашборд

2023-11-20 15:57 UTC, SabinaValeriia commented
![Снимок экрана 2023-11-20 в 17 52 59](https://github.com/SabinaValeriia/intership-second/assets/116557806/942511ee-cda5-4992-ae64-1c1813a8d82e)
![Снимок экрана 2023-11-20 в 17 55 30](https://github.com/SabinaValeriia/intership-second/assets/116557806/84a2da4a-1b13-4896-9a18-e2f9b704eade)
для тесту змінила колір для outline hover , вони збігаються по розмірам

2023-11-21 09:21 UTC, merged